import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavbarMain from '../component/nav'
import Image from 'next/image'
import laundrybanner from "../public/src/images/laundry-banner.png"
import Getmachine from '../functions/fatch.machine'
import GetBusyMachine from '../functions/fatch.busy.machine'
import Ads from '../component/advertist'
import MidleStrip from '../component/midlestrip'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin = "true"></link>
        <link href="https://fonts.googleapis.com/css2?family=Coiny&display=swap" rel="stylesheet"></link>
      </Head>
      <NavbarMain />
      <main className={styles.main}>
        <div className='row px-3 py-3 mt-4'>
          <div className='col-12 col-lg-5'>
            <Ads />
          </div>
          <div className='col-12 col-lg-7'>
            <div className='banner'>

              <Image
                alt="laundry shop banner"
                src={laundrybanner}
                width={750}
                height={379}
                style={{
                  width: '90%',
                  height: 'auto',
                }}
              />
            </div>
          </div>
        </div>

        <MidleStrip />
        <h1 className='idle py-2'>Idle Machine</h1>
        <Getmachine/>
        <h1 className='busy py-2'>Busy Machine</h1>
        <GetBusyMachine />

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>

  )
}
